# -*- coding: utf-8 -*-
"""ablation study NDIEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3yyqZDk2vk-dE8JlOWtLpE7BuVHaTdd
"""

!pip install lxml -q
from google.colab import files
print("Upload: the 3 JSON files AND drone.xsd")
uploaded = files.upload()
print("\nUploaded:", list(uploaded.keys()))

from google.colab import drive
drive.mount('/content/drive')

import json
for f in ['Crazyflie results.JSON', 'hexacopter results.JSON', 'tello results.JSON']:
    d = json.load(open(f))
    print(f, '→', len(d), 'records')
    print('  first record:', d[0])
    print()

for f in ['Crazyflie results.JSON', 'hexacopter results.JSON', 'tello results.JSON']:
    print('='*60)
    print(f)
    print('='*60)
    print(open(f).read()[:400])
    print()

import re, json

# your uploaded filenames (console logs) -> clean output names
FILES = {
    'crazyflie':  ('Crazyflie results.JSON',  'crazyflie_clean.json',  'CRAZYFLIE_TELEMETRY'),
    'hexacopter': ('hexacopter results.JSON',  'hexacopter_clean.json', 'MAVLINK'),
    'tello':      ('tello results.JSON',        'tello_clean.json',      'TELLO_STATE'),
}

def extract(text):
    """Recover every balanced {...} block that follows a [n/N] marker or contains telemetry."""
    records, depth, start = [], 0, None
    for i, ch in enumerate(text):
        if ch == '{':
            if depth == 0: start = i
            depth += 1
        elif ch == '}':
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    blob = text[start:i+1]
                    # python-dict style (single quotes) -> JSON
                    try:
                        d = json.loads(blob)
                    except json.JSONDecodeError:
                        try:
                            d = json.loads(blob.replace("'", '"'))
                        except json.JSONDecodeError:
                            start = None; continue
                    records.append(d)
                    start = None
    return records

for plat, (src, out, mtype) in FILES.items():
    text = open(src, encoding='utf-8', errors='ignore').read()
    raw = extract(text)
    recs = []
    for d in raw:
        tel = d.get('data', d.get('telemetry', d))   # handle wrapped or bare dicts
        recs.append({
            'capture_time': d.get('capture_time'),
            'message_type': d.get('message_type', mtype),
            'telemetry': tel,
        })
    json.dump(recs, open(out, 'w'), indent=2)
    print(f"{plat:12s}: {len(recs):4d} records  ->  {out}")
    if recs:
        print(f"             first fields: {list(recs[0]['telemetry'].keys())[:6]}")
    print()

import re, json

FILES = {
    'crazyflie':  ('Crazyflie results.JSON',  'crazyflie_clean.json',  'CRAZYFLIE_TELEMETRY'),
    'hexacopter': ('hexacopter results.JSON',  'hexacopter_clean.json', 'MAVLINK'),
    'tello':      ('tello results.JSON',        'tello_clean.json',      'TELLO_STATE'),
}

def extract(text):
    records, depth, start = [], 0, None
    for i, ch in enumerate(text):
        if ch == '{':
            if depth == 0: start = i
            depth += 1
        elif ch == '}':
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    blob = text[start:i+1]
                    try:
                        d = json.loads(blob)
                    except json.JSONDecodeError:
                        try:
                            d = json.loads(blob.replace("'", '"'))
                        except json.JSONDecodeError:
                            start = None; continue
                    if isinstance(d, dict):
                        records.append(d)
                    start = None
    return records

for plat, (src, out, mtype) in FILES.items():
    text = open(src, encoding='utf-8', errors='ignore').read()
    raw = extract(text)
    recs = []
    for d in raw:
        tel = d.get('data', d.get('telemetry', d))
        if not isinstance(tel, dict):      # skip anything that isn't a telemetry dict
            continue
        recs.append({
            'capture_time': d.get('capture_time'),
            'message_type': d.get('message_type', mtype),
            'telemetry': tel,
        })
    json.dump(recs, open(out, 'w'), indent=2)
    print(f"{plat:12s}: {len(recs):4d} clean records -> {out}")
    if recs:
        print(f"             sample fields: {list(recs[0]['telemetry'].keys())[:8]}")
    print()

import re, json

FILES = {
    'crazyflie':  ('Crazyflie results.JSON',  'crazyflie_clean.json',  'CRAZYFLIE_TELEMETRY'),
    'hexacopter': ('hexacopter results.JSON',  'hexacopter_clean.json', 'MAVLINK'),
    'tello':      ('tello results.JSON',        'tello_clean.json',      'TELLO_STATE'),
}

def extract(text):
    records, depth, start = [], 0, None
    for i, ch in enumerate(text):
        if ch == '{':
            if depth == 0: start = i
            depth += 1
        elif ch == '}':
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    blob = text[start:i+1]
                    try:
                        d = json.loads(blob)
                    except json.JSONDecodeError:
                        try:
                            d = json.loads(blob.replace("'", '"'))
                        except json.JSONDecodeError:
                            start = None; continue
                    if isinstance(d, dict):
                        records.append(d)
                    start = None
    return records

for plat, (src, out, mtype) in FILES.items():
    text = open(src, encoding='utf-8', errors='ignore').read()
    raw = extract(text)
    recs = []
    for d in raw:
        tel = d.get('data', d.get('telemetry', d))
        if not isinstance(tel, dict):      # skip anything that isn't a telemetry dict
            continue
        recs.append({
            'capture_time': d.get('capture_time'),
            'message_type': d.get('message_type', mtype),
            'telemetry': tel,
        })
    json.dump(recs, open(out, 'w'), indent=2)
    print(f"{plat:12s}: {len(recs):4d} clean records -> {out}")
    if recs:
        print(f"             sample fields: {list(recs[0]['telemetry'].keys())[:8]}")
    print()

import json
from collections import Counter

d = json.load(open('hexacopter_clean.json'))
print("total:", len(d))
types = Counter(r['telemetry'].get('mavpackettype', r.get('message_type')) for r in d)
print("\nmessage types:")
for t, n in types.most_common():
    print(f"  {t:28s} {n}")

# show one ATTITUDE record in full, if present
for r in d:
    if r['telemetry'].get('mavpackettype') == 'ATTITUDE':
        print("\nsample ATTITUDE record:")
        print(r['telemetry'])
        break

import json, time, random, statistics
from lxml import etree

NS = "http://finalNdiem/1.0"
NSMAP = {None: NS}
SCHEMA = etree.XMLSchema(etree.parse("drone.xsd"))

FILES = {"crazyflie":"crazyflie_clean.json",
         "hexacopter":"hexacopter_clean.json",
         "tello":"tello_clean.json"}

N_RUNS, DEGRADE_FRACTION, FAULT_FRACTION = 10, 0.35, 0.30
NDIEM_ELEMENT = {"battery_pct":"chargePercent","battery_voltage":"chargeValue"}
VALID_RANGE = {"roll":(-180,180),"pitch":(-180,180),"yaw":(-180,180),"battery_pct":(0,100)}

# ---------- mappers (native fields -> NDIEM fields) ----------
def map_crazyflie(r):
    t=r["telemetry"]; return {"roll":t["stabilizer.roll"],"pitch":t["stabilizer.pitch"],"yaw":t["stabilizer.yaw"]}
def map_tello(r):
    t=r["telemetry"]; return {"roll":t["roll"],"pitch":t["pitch"],"yaw":t["yaw"],
        "vx":t["vgx"],"vy":t["vgy"],"vz":t["vgz"],"alt":t["h"],"battery_pct":t["bat"]}
def map_hexacopter(r):
    t=r["telemetry"];

"""ABLATION STUDY"""

# =====================================================================
# NDIEM EVALUATION — self-contained notebook code
# Upload first: crazyflie_clean.json, hexacopter_clean.json,
#               tello_clean.json, drone.xsd
# =====================================================================
import json, time, random, statistics
from lxml import etree

NS = "http://finalNdiem/1.0"
NSMAP = {None: NS}
SCHEMA = etree.XMLSchema(etree.parse("drone.xsd"))

FILES = {"crazyflie": "crazyflie_clean.json",
         "hexacopter": "hexacopter_clean.json",
         "tello": "tello_clean.json"}

N_RUNS, DEGRADE_FRACTION, FAULT_FRACTION = 10, 0.35, 0.30
NDIEM_ELEMENT = {"battery_pct": "chargePercent", "battery_voltage": "chargeValue"}
VALID_RANGE = {"roll": (-180, 180), "pitch": (-180, 180),
               "yaw": (-180, 180), "battery_pct": (0, 100)}

INFO = {"crazyflie":  ("CF-01",   "Bitcraze",  "Crazyflie 2.1", "Micro-quadrotor"),
        "hexacopter": ("HEX-01",  "ArduPilot", "Hexacopter",    "Hexarotor"),
        "tello":      ("TELLO-01","Ryze/DJI",  "Tello EDU",     "Micro-quadrotor")}

# =====================================================================
# PROTOCOL ADAPTERS  (native protocol fields -> common NDIEM fields)
# =====================================================================
def map_crazyflie(r):
    t = r["telemetry"]
    return {"roll": t["stabilizer.roll"], "pitch": t["stabilizer.pitch"],
            "yaw": t["stabilizer.yaw"]}

def map_tello(r):
    t = r["telemetry"]
    return {"roll": t["roll"], "pitch": t["pitch"], "yaw": t["yaw"],
            "vx": t["vgx"], "vy": t["vgy"], "vz": t["vgz"],
            "alt": t["h"], "battery_pct": t["bat"]}

def map_hexacopter(r):
    t = r["telemetry"]; m = t.get("mavpackettype")
    if m == "ATTITUDE":
        return {"roll": t["roll"], "pitch": t["pitch"], "yaw": t["yaw"]}
    if m == "LOCAL_POSITION_NED":
        return {"lat": t["x"], "lon": t["y"], "alt": -t["z"],
                "vx": t["vx"], "vy": t["vy"], "vz": t["vz"]}
    if m == "SYS_STATUS":
        return {"battery_pct": max(t["battery_remaining"], 0),
                "battery_voltage": t["voltage_battery"] / 1000.0}
    if m == "BATTERY_STATUS":
        return {"battery_pct": max(t["battery_remaining"], 0)}
    if m == "VFR_HUD":
        return {"alt": t["alt"]}
    if m == "ALTITUDE":
        return {"alt": t["altitude_relative"]}
    return {}

MAPPERS = {"crazyflie": map_crazyflie,
           "hexacopter": map_hexacopter,
           "tello": map_tello}

# =====================================================================
# MESSAGE HANDLER LAYER  (transformation + serialization stages)
# =====================================================================
def S(parent, tag, txt=None):
    e = etree.SubElement(parent, f"{{{NS}}}{tag}")
    if txt is not None:
        e.text = str(txt)
    return e

def build_tree(platform, mp, mid):
    """
    Transformation stage: transforms an extracted native UAV message
    into its NDIEM XML representation (an in-memory element tree).
    Excludes serialization and validation.
    """
    i = INFO[platform]
    root = etree.Element(f"{{{NS}}}NDIEMMessage", nsmap=NSMAP)
    S(root, "messageID", mid); S(root, "timestamp", "2025-01-01T00:00:00")
    h = S(root, "Header"); S(h, "senderID", platform); S(h, "receiverID", "GCS")
    idn = S(root, "UavIdentificationData")
    S(idn, "uavID", i[0]); S(idn, "uavManufacturer", i[1])
    S(idn, "uavModel", i[2]); S(idn, "uavType", i[3])
    ori = all(k in mp for k in ("roll", "pitch", "yaw"))
    vel = all(k in mp for k in ("vx", "vy", "vz"))
    pos = any(k in mp for k in ("lat", "lon", "alt"))
    bat = "battery_pct" in mp
    if ori or vel or pos or bat:
        tel = S(root, "UavTelemetryData")
        S(tel, "telemetryTimestamp", "2025-01-01T00:00:00"); S(tel, "status", "OK")
        if bat:
            b = S(tel, "UavBattery")
            S(b, "chargeValue", mp.get("battery_voltage", mp["battery_pct"]))
            S(b, "chargePercent", int(mp["battery_pct"]))
        if ori:
            o = S(tel, "UavOrientation")
            S(o, "pitch", mp["pitch"]); S(o, "yaw", mp["yaw"]); S(o, "roll", mp["roll"])
        if vel:
            v = S(tel, "UavVelocity")
            S(v, "vx", mp["vx"]); S(v, "vy", mp["vy"]); S(v, "vz", mp["vz"])
        if pos:
            ps = S(tel, "UavPosition")
            S(ps, "lat", mp.get("lat", 0.0)); S(ps, "lon", mp.get("lon", 0.0))
            S(ps, "alt", mp.get("alt", 0.0))
    return root                       # returns the TREE, not bytes

def serialize(root):
    """Serialization stage: XML tree -> byte string."""
    return etree.tostring(root)

def build(platform, mp, mid):
    """Transform + serialize, for callers that need bytes."""
    return serialize(build_tree(platform, mp, mid))

# =====================================================================
# RECEIVER / GCS  (parse and consume NDIEM messages)
# =====================================================================
def parse(xb):
    root = etree.fromstring(xb); out = {}
    for el in root.iter():
        tag = etree.QName(el).localname
        if el.text and el.text.strip():
            out[tag] = el.text.strip()
    return out

def receiver_can_consume(parsed, truth, cfg):
    if cfg == "no_xml_schema":
        return False
    exp = list(truth.keys())
    return bool(exp) and all(NDIEM_ELEMENT.get(k, k) in parsed for k in exp)

def match(pv, sv):
    if pv is None:
        return False
    try:
        return abs(float(pv) - float(sv)) < 1e-6
    except (ValueError, TypeError):
        return str(pv) == str(sv)

# =====================================================================
# FAULT MODEL  (emulates link corruption; NOT from the drones)
# =====================================================================
def inject(mp, rng):
    ks = list(mp.keys())
    if not ks:
        return dict(mp), None
    f = rng.choice(ks); out = dict(mp); k = rng.choice(["trunc", "corrupt", "range"])
    if k == "trunc":
        del out[f]
    elif k == "corrupt":
        out[f] = "##BAD##"
    else:
        out[f] = VALID_RANGE.get(f, (-1e6, 1e6))[1] * 1000
    return out, f

def corrupt_map(mp):
    ks = list(mp.keys())
    if len(ks) < 2:
        return dict(mp)
    vs = [mp[k] for k in ks]
    return dict(zip(ks, vs[-1:] + vs[:-1]))

# =====================================================================
# LOAD DATA
# =====================================================================
DATA = {p: json.load(open(f)) for p, f in FILES.items()}
CONFIGS = ["full", "no_validator", "no_xml_schema",
           "no_message_bus", "degraded_mapping"]

# =====================================================================
# ABLATION — one run of one configuration
# =====================================================================
def run_once(cfg, cond, rng):
    msgs = iok = vok = fld = fok = finj = fcau = 0
    for p, recs in DATA.items():
        mp_fn = MAPPERS[p]
        for idx, rec in enumerate(recs):
            truth = mp_fn(rec)
            if not truth:
                continue
            em = truth; fault = None
            if cond == "faulted" and rng.random() < FAULT_FRACTION:
                em, fault = inject(truth, rng)
                if fault:
                    finj += 1
            if cfg == "degraded_mapping" and rng.random() < DEGRADE_FRACTION:
                em = corrupt_map(em)
            if cfg == "no_xml_schema":
                parsed = {k: str(v) for k, v in em.items()}; valid = None; deliver = True
            else:
                try:
                    xb = build(p, em, f"{p}-{idx}")
                except Exception:
                    if fault:
                        fcau += 1
                    continue
                if cfg == "no_validator":
                    valid = None; deliver = True
                else:
                    valid = SCHEMA.validate(etree.fromstring(xb)); deliver = bool(valid)
                    if fault and not valid:
                        fcau += 1
                parsed = parse(xb)
            msgs += 1
            if valid is True:
                vok += 1
            if deliver and receiver_can_consume(parsed, truth, cfg):
                iok += 1
            for k, sv in truth.items():
                fld += 1
                if deliver and match(parsed.get(NDIEM_ELEMENT.get(k, k)), sv):
                    fok += 1
    return dict(msgs=msgs, iok=iok,
                vok=(vok if cfg not in ("no_validator", "no_xml_schema") else None),
                fld=fld, fok=fok, finj=finj, fcau=fcau)

# =====================================================================
# RUN ABLATION
# =====================================================================
print(f"{'='*72}\nNDIEM ABLATION — {N_RUNS} runs on real captured data\n{'='*72}")
for p in DATA:
    print(f"  {p:12s}{len(DATA[p])} records")

for cond in ("clean", "faulted"):
    print(f"\n{'='*72}\nCONDITION: {cond}\n{'='*72}")
    for cfg in CONFIGS:
        runs = [run_once(cfg, cond, random.Random(5000 + r)) for r in range(N_RUNS)]
        M, F = runs[0]["msgs"], runs[0]["fld"]
        io = [100*r["iok"]/r["msgs"] for r in runs]
        ig = [100*r["fok"]/r["fld"] for r in runs]
        print(f"\n{cfg}")
        print(f"   interoperability {statistics.mean(io):6.2f}% ± {statistics.stdev(io):.3f}  [{runs[0]['iok']}/{M}]")
        print(f"   data integrity   {statistics.mean(ig):6.2f}% ± {statistics.stdev(ig):.3f}  [{runs[0]['fok']}/{F}]")
        if runs[0]["vok"] is not None:
            v = [100*r["vok"]/r["msgs"] for r in runs]
            print(f"   validation       {statistics.mean(v):6.2f}%  [{runs[0]['vok']}/{M}]")
        else:
            print("   validation       N/A (no validator or schema)")
        if cond == "faulted":
            fd = [100*r["fcau"]/r["finj"] if r["finj"] else 0 for r in runs]
            print(f"   fault detection  {statistics.mean(fd):6.2f}% ± {statistics.stdev(fd):.3f}  [{runs[0]['fcau']}/{runs[0]['finj']}]")

# =====================================================================
# LATENCY & MESSAGE SIZE — transformation vs end-to-end
#   transformation latency  = build_tree only        (Table 6)
#   end-to-end latency      = build_tree + serialize + validate  (Table 4)
# =====================================================================
print(f"\n{'='*72}\nLATENCY AND MESSAGE SIZE\n{'='*72}")
RUNS = 5
print(f"{'platform':<12}{'N':>6}{'transform_ms':>14}{'sd':>8}"
      f"{'end2end_ms':>12}{'sd':>8}{'ndiem_B':>9}{'native_B':>10}")
print("-"*79)
for p, recs in DATA.items():
    tr_runs = []; e2e_runs = []
    for _ in range(RUNS):
        tr = []; e2e = []
        for i, rec in enumerate(recs):
            mp = MAPPERS[p](rec)
            if not mp:
                continue
            t0 = time.perf_counter()
            tree = build_tree(p, mp, f"{p}-{i}")     # transformation only
            t1 = time.perf_counter()                 # Table 6 stops here
            xb = serialize(tree)                     # serialization
            SCHEMA.validate(tree)                    # validation
            t2 = time.perf_counter()                 # Table 4 stops here
            tr.append((t1-t0)*1000); e2e.append((t2-t0)*1000)
        tr_runs.append(statistics.mean(tr)); e2e_runs.append(statistics.mean(e2e))
    # sizes
    sizes = []; native = []; n = 0
    for i, rec in enumerate(recs):
        mp = MAPPERS[p](rec)
        if not mp:
            continue
        n += 1
        sizes.append(len(build(p, mp, f"{p}-{i}")))
        native.append(len(json.dumps(rec["telemetry"], separators=(",", ":"))))
    print(f"{p:<12}{n:>6}{statistics.mean(tr_runs):>14.4f}{statistics.stdev(tr_runs):>8.4f}"
          f"{statistics.mean(e2e_runs):>12.4f}{statistics.stdev(e2e_runs):>8.4f}"
          f"{statistics.mean(sizes):>9.0f}{statistics.mean(native):>10.0f}")

# =====================================================================
# Ablation figures from the run results.
# Paste as a Colab cell and run. Produces two 300-DPI figures and
# downloads them.
# =====================================================================
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files

plt.rcParams.update({
    "font.family": "DejaVu Sans", "font.size": 12, "axes.titlesize": 14,
    "axes.labelsize": 13, "xtick.labelsize": 10, "ytick.labelsize": 11,
    "legend.fontsize": 10, "figure.dpi": 300,
})

configs = ["Full", "No\nValidator", "No XML\nSchema", "No Message\nBus", "Degraded\nMapping"]
x = np.arange(len(configs)); w = 0.25
BLUE, ORANGE, GREEN, RED = "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"

# ---- values from YOUR run (N/A entered as 0 and hatched) ----
clean = {
    "interop":    [100.0, 100.0,   0.0, 100.0, 100.0],
    "integrity":  [100.0, 100.0,  91.78,100.0,  70.32],
    "validation": [100.0, None,   None, 100.0, 100.0],
}
faulted = {
    "interop":    [80.67, 90.27,   0.0, 80.67, 80.92],
    "integrity":  [83.52, 90.84,  86.24,83.52, 59.75],
    "validation": [90.40, None,   None, 90.40, 90.69],
    "faultdet":   [34.06,  2.21,   0.0, 34.06, 32.91],
}

def bars(ax, vals, offset, color, label):
    heights = [v if v is not None else 0 for v in vals]
    b = ax.bar(x + offset, heights, w, color=color, label=label)
    for xi, v in zip(x + offset, vals):          # mark N/A
        if v is None:
            ax.text(xi, 2, "N/A", ha="center", va="bottom",
                    fontsize=8, rotation=90, color="gray")
    return b

# ---------- Figure 1: clean condition ----------
fig, ax = plt.subplots(figsize=(9, 5))
bars(ax, clean["interop"],   -w, BLUE,   "Interoperability (%)")
bars(ax, clean["integrity"],  0, ORANGE, "Data Integrity (%)")
bars(ax, clean["validation"], w, GREEN,  "Validation (%)")
ax.set_ylabel("Percentage (%)"); ax.set_ylim(0, 105)
ax.set_xticks(x); ax.set_xticklabels(configs)
ax.set_title("Ablation Study — Clean Telemetry", fontweight="bold")
ax.legend(loc="lower left", framealpha=0.9)
ax.grid(axis="y", linestyle="--", alpha=0.4)
fig.tight_layout(); fig.savefig("ablation_clean.png", dpi=300, bbox_inches="tight")
fig.savefig("ablation_clean.pdf", bbox_inches="tight"); plt.show()

# ---------- Figure 2: faulted condition (four metrics) ----------
w2 = 0.20
fig, ax = plt.subplots(figsize=(9.5, 5))
bars_off = [-1.5*w2, -0.5*w2, 0.5*w2, 1.5*w2]
for vals, off, col, lab in [
    (faulted["interop"],   bars_off[0], BLUE,   "Interoperability (%)"),
    (faulted["integrity"], bars_off[1], ORANGE, "Data Integrity (%)"),
    (faulted["validation"],bars_off[2], GREEN,  "Validation (%)"),
    (faulted["faultdet"],  bars_off[3], RED,    "Fault Detection (%)"),
]:
    heights = [v if v is not None else 0 for v in vals]
    ax.bar(x + off, heights, w2, color=col, label=lab)
    for xi, v in zip(x + off, vals):
        if v is None:
            ax.text(xi, 2, "N/A", ha="center", va="bottom",
                    fontsize=8, rotation=90, color="gray")
ax.set_ylabel("Percentage (%)"); ax.set_ylim(0, 105)
ax.set_xticks(x); ax.set_xticklabels(configs)
ax.set_title("Ablation Study — 30% Faulted Telemetry", fontweight="bold")
ax.legend(loc="upper right", framealpha=0.9, ncol=2)
ax.grid(axis="y", linestyle="--", alpha=0.4)
fig.tight_layout(); fig.savefig("ablation_faulted.png", dpi=300, bbox_inches="tight")
fig.savefig("ablation_faulted.pdf", bbox_inches="tight"); plt.show()

for f in ["ablation_clean.png","ablation_clean.pdf",
          "ablation_faulted.png","ablation_faulted.pdf"]:
    files.download(f)

import json, time, statistics

# reuse build(), MAPPERS, DATA from the ablation cell (run that first)

RUNS = 5
print(f"{'platform':<12}{'N':>6}{'transform_ms':>14}{'sd':>10}{'ndiem_B':>10}{'native_B':>10}")
print("-"*62)
rows={}
for p, recs in DATA.items():
    per_run=[]
    for _ in range(RUNS):
        lat=[]
        for i,rec in enumerate(recs):
            mp=MAPPERS[p](rec)
            if not mp: continue
            t0=time.perf_counter()
            xb=build(p,mp,f"{p}-{i}")
            lat.append((time.perf_counter()-t0)*1000)
        per_run.append(statistics.mean(lat))
    # sizes and native comparison
    sizes=[]; native=[]; n=0
    for i,rec in enumerate(recs):
        mp=MAPPERS[p](rec)
        if not mp: continue
        n+=1
        sizes.append(len(build(p,mp,f"{p}-{i}")))
        native.append(len(json.dumps(rec["telemetry"],separators=(",",":"))))
    tm=statistics.mean(per_run); sd=statistics.stdev(per_run)
    rows[p]=(n,tm,sd,statistics.mean(sizes),statistics.mean(native))
    print(f"{p:<12}{n:>6}{tm:>14.4f}{sd:>10.4f}{statistics.mean(sizes):>10.0f}{statistics.mean(native):>10.0f}")

"""Latency track back for ablation study"""

import time, statistics
from lxml import etree

RUNS = 5
print(f"{'platform':<12}{'N':>6}{'end_to_end_ms':>15}{'sd':>10}")
print("-"*43)
overall=[]
for p, recs in DATA.items():
    per_run=[]
    for _ in range(RUNS):
        lat=[]
        for i,rec in enumerate(recs):
            mp=MAPPERS[p](rec)
            if not mp: continue
            t0=time.perf_counter()
            xb=build(p,mp,f"{p}-{i}")          # extract + transform
            SCHEMA.validate(etree.fromstring(xb))  # validate
            _=xb.decode()                      # serialise
            lat.append((time.perf_counter()-t0)*1000)
        per_run.append(statistics.mean(lat))
    tm=statistics.mean(per_run); sd=statistics.stdev(per_run)
    overall.append(tm)
    print(f"{p:<12}{len([r for r in recs if MAPPERS[p](r)]):>6}{tm:>15.4f}{sd:>10.4f}")
print(f"\noverall end-to-end mean: {statistics.mean(overall):.4f} ms")

"""latency for table 4"""

import time, statistics
from lxml import etree
RUNS=5
print(f"{'platform':<12}{'N':>6}{'transform_ms':>14}{'end2end_ms':>13}")
print("-"*45)
for p,recs in DATA.items():
    tr_runs=[]; e2e_runs=[]
    for _ in range(RUNS):
        tr=[]; e2e=[]
        for i,rec in enumerate(recs):
            mp=MAPPERS[p](rec)
            if not mp: continue
            t0=time.perf_counter(); xb=build(p,mp,f"{p}-{i}"); t1=time.perf_counter()
            SCHEMA.validate(etree.fromstring(xb)); _=xb.decode(); t2=time.perf_counter()
            tr.append((t1-t0)*1000); e2e.append((t2-t0)*1000)
        tr_runs.append(statistics.mean(tr)); e2e_runs.append(statistics.mean(e2e))
    print(f"{p:<12}{len([r for r in recs if MAPPERS[p](r)]):>6}"
          f"{statistics.mean(tr_runs):>14.4f}{statistics.mean(e2e_runs):>13.4f}")

import matplotlib.pyplot as plt
import numpy as np

# ============================================================
# Values EXACTLY as they appear in the ablation table
# (clean condition, user's frozen 995-file run)
# ============================================================
configs   = ["Full\nNDIEM+XML", "No\nValidator", "No XML\nSchema",
             "No Message\nBus", "Degraded\nMapping"]
interop   = [100.0, 100.0,   0.0, 100.0, 100.0]
integrity = [100.0, 100.0, 91.78, 100.0,  69.93]
validation= [100.0, None,  None, 100.0, 100.0]     # None -> N/A
latency   = [0.0445, 0.0386, 0.0022, 0.0421, 0.0413]

x = np.arange(len(configs)); w = 0.25
plt.rcParams.update({"font.size": 12, "figure.dpi": 300})
BLUE, ORANGE, GREEN, LINE = "#1f77b4", "#ff7f0e", "#2ca02c", "#17384f"

fig, ax1 = plt.subplots(figsize=(9, 5))

def draw(vals, off, color, label):
    heights = [v if v is not None else 0 for v in vals]
    ax1.bar(x + off, heights, w, color=color, label=label)
    for xi, v in zip(x + off, vals):
        if v is None:
            ax1.text(xi, 2, "N/A", ha="center", va="bottom",
                     fontsize=8, rotation=90, color="gray")

draw(interop,    -w, BLUE,   "Interoperability (%)")
draw(integrity,   0, ORANGE, "Data Integrity (%)")
draw(validation,  w, GREEN,  "Validation (%)")

ax1.set_ylabel("Percentage (%)"); ax1.set_ylim(0, 108)
ax1.set_xticks(x); ax1.set_xticklabels(configs)
ax1.set_title("Ablation Study of NDIEM Components", fontweight="bold")

# value labels on the percentage bars
for xi, v in zip(x - w, interop):    ax1.text(xi, v+1, f"{v:.0f}", ha="center", fontsize=8)
for xi, v in zip(x,     integrity):  ax1.text(xi, v+1, f"{v:.2f}", ha="center", fontsize=8)
for xi, v in zip(x + w, validation):
    if v is not None: ax1.text(xi, v+1, f"{v:.0f}", ha="center", fontsize=8)

ax2 = ax1.twinx()
ax2.plot(x, latency, color=LINE, marker="o", lw=2, label="End-to-End Latency (ms)")
for xi, v in zip(x, latency):
    ax2.annotate(f"{v:.4f}", (xi, v), textcoords="offset points",
                 xytext=(0, 8), ha="center", fontsize=8, color=LINE)
ax2.set_ylabel("End-to-End Latency (ms)", color=LINE)
ax2.set_ylim(0, max(latency)*1.4); ax2.tick_params(axis="y", labelcolor=LINE)

l1, lab1 = ax1.get_legend_handles_labels()
l2, lab2 = ax2.get_legend_handles_labels()
ax1.legend(l1 + l2, lab1 + lab2, loc="center left", framealpha=0.9, fontsize=9)
ax1.grid(axis="y", linestyle="--", alpha=0.4)

fig.tight_layout()
fig.savefig("ablation_final.png", dpi=300, bbox_inches="tight")
fig.savefig("ablation_final.pdf", bbox_inches="tight")
print("saved")

import time, statistics
from lxml import etree
RUNS = 5
print(f"{'platform':<12}{'N':>6}{'transform_ms':>14}{'sd':>9}{'end2end_ms':>13}{'sd':>9}{'overhead':>10}")
print("-"*73)
for p, recs in DATA.items():
    tr_r=[]; e2e_r=[]
    for _ in range(RUNS):
        tr=[]; e2e=[]
        for i,rec in enumerate(recs):
            mp=MAPPERS[p](rec)
            if not mp: continue
            t0=time.perf_counter(); tree=build_tree(p,mp,f"{p}-{i}"); t1=time.perf_counter()
            xb=serialize(tree); SCHEMA.validate(tree); t2=time.perf_counter()
            tr.append((t1-t0)*1000); e2e.append((t2-t0)*1000)
        tr_r.append(statistics.mean(tr)); e2e_r.append(statistics.mean(e2e))
    n=len([r for r in recs if MAPPERS[p](r)])
    tm=statistics.mean(tr_r); em=statistics.mean(e2e_r)
    print(f"{p:<12}{n:>6}{tm:>14.4f}{statistics.stdev(tr_r):>9.4f}{em:>13.4f}{statistics.stdev(e2e_r):>9.4f}{em-tm:>10.4f}")

"""LATENCY GRAPH"""

import matplotlib.pyplot as plt
import numpy as np

# ============================================================
# Values EXACTLY as in Table (Section 5.5.2), frozen run
# ============================================================
platforms   = ["Crazyflie", "Hexacopter", "Tello EDU"]
transform   = [0.049, 0.057, 0.073]
end_to_end  = [0.062, 0.072, 0.092]
tr_err      = [0.001, 0.011, 0.001]
e2e_err     = [0.001, 0.014, 0.002]

x = np.arange(len(platforms)); w = 0.35
plt.rcParams.update({"font.size": 12, "figure.dpi": 300})

fig, ax = plt.subplots(figsize=(8, 5))
b1 = ax.bar(x - w/2, transform, w, yerr=tr_err, capsize=4,
            color="#1f77b4", label="Transformation Latency (ms)")
b2 = ax.bar(x + w/2, end_to_end, w, yerr=e2e_err, capsize=4,
            color="#ff7f0e", label="End-to-End Processing Time (ms)")

# value labels
for xi, v in zip(x - w/2, transform):
    ax.text(xi, v + 0.003, f"{v:.3f}", ha="center", fontsize=9)
for xi, v in zip(x + w/2, end_to_end):
    ax.text(xi, v + 0.003, f"{v:.3f}", ha="center", fontsize=9)

ax.set_ylabel("Latency (ms)")
ax.set_xlabel("UAV Platform")
ax.set_xticks(x); ax.set_xticklabels(platforms)
ax.set_ylim(0, 0.11)
ax.set_title("Transformation Latency vs. End-to-End Processing Time",
             fontweight="bold")
ax.legend(framealpha=0.9)
ax.grid(axis="y", linestyle="--", alpha=0.4)

fig.tight_layout()
fig.savefig("latency_graph.png", dpi=300, bbox_inches="tight")
fig.savefig("latency_graph.pdf", bbox_inches="tight")
print("saved")

"""Bar GRAPH"""

import matplotlib.pyplot as plt
import numpy as np
from google.colab import files

# values EXACTLY as in the table (frozen run)
platforms  = ["Crazyflie", "Hexacopter", "Tello EDU"]
transform  = [0.049, 0.057, 0.073]
end_to_end = [0.062, 0.072, 0.092]
overhead   = [0.013, 0.015, 0.019]


x = np.arange(len(platforms)); w = 0.25
plt.rcParams.update({"font.size": 12, "figure.dpi": 300})

fig, ax = plt.subplots(figsize=(9, 5))
ax.bar(x - w, transform,  w, color="#1f77b4", label="Transformation Latency (ms)")
ax.bar(x,     end_to_end, w, color="#ff7f0e", label="End-to-End Processing Time (ms)")
ax.bar(x + w, overhead,   w, color="#2ca02c", label="Overhead (ms)")

for xi, v in zip(x - w, transform):
    ax.text(xi, v + 0.002, f"{v:.3f}", ha="center", fontsize=9)
for xi, v in zip(x, end_to_end):
    ax.text(xi, v + 0.002, f"{v:.3f}", ha="center", fontsize=9)
for xi, v in zip(x + w, overhead):
    ax.text(xi, v + 0.002, f"{v:.3f}", ha="center", fontsize=9)

ax.set_ylabel("Latency (ms)")
ax.set_xlabel("UAV Platform")
ax.set_xticks(x); ax.set_xticklabels(platforms)
ax.set_ylim(0, 0.105)
ax.set_title("Transformation, End-to-End, and Overhead Latency of NDIEM",
             fontweight="bold")
ax.legend(framealpha=0.9, fontsize=9)
ax.grid(axis="y", linestyle="--", alpha=0.4)

fig.tight_layout()
fig.savefig("latency_bars.png", dpi=300, bbox_inches="tight")
fig.savefig("latency_bars.pdf", bbox_inches="tight")
plt.show()
from google.colab import files
files.download("latency_bars.pdf")
files.download("latency_bars.png")